"""empty message

Revision ID: 23c8c954bd87
Revises: 5d3de377eae4
Create Date: 2020-07-23 12:53:45.012662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c8c954bd87'
down_revision = '5d3de377eae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'freetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('freetime', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
