"""empty message

Revision ID: b82e8f90afe2
Revises: ef65d47cb1ba
Create Date: 2020-07-23 13:55:04.339212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82e8f90afe2'
down_revision = 'ef65d47cb1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('childgender', sa.Integer(), nullable=True),
    sa.Column('childage', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_identity', table_name='user')
    op.create_index(op.f('ix_user_identity'), 'user', ['identity'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identity'), table_name='user')
    op.create_index('ix_user_identity', 'user', ['identity'], unique=False)
    op.drop_table('children')
    # ### end Alembic commands ###
